# Generated by Django 2.2 on 2021-08-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Updated_at',
            new_name='updated_at',
        ),
    ]
